name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lib:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get -y install libclang-dev libmetis-dev
    - uses: actions/checkout@v4
    - name: Fmt
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy (with metis)
      run: cargo clippy --features=metis
    - name: Run tests (with metis)
      run: cargo test --verbose --features=metis

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y gmsh libclang-dev libmetis-dev
    - name: Run examples/dual_mesh_2d
      run: cargo run --example dual_mesh_2d --release
    - name: Run examples/partition_3d
      run: cargo run --example partition_3d --release --features=metis

  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y gmsh libclang-dev libmetis-dev
    - name: Python bindings
      run: |
        cd pytmesh
        pip install vtk==9.3
        pip install -e .
        python -m unittest discover
    - name: Python bindings (with metis)
      run: |
        cd pytmesh
        pip install vtk==9.3
        echo "" >> pyproject.toml
        echo "[tool.maturin]" >> pyproject.toml
        echo "features = [\"metis\"]" >> pyproject.toml
        pip install -e .
        python -c "import pytmesh; assert pytmesh.HAVE_METIS"
        python -m unittest discover
